# Generated by Django 4.2.5 on 2023-12-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
